### ISSUE TITLE
Helpers for Unity Should have Unity updated to 5.0.1

### ISSUE THREAD

**Issue by rasmusbjoernrasmussen** [dansiegel/AzureMobileClient.Helpers#12]
Getting error if using the pre-release of the Unity DI Helpers because that Unity is only version 4 and still using Microsoft.Practices Namespace.

**Comment by dansiegel** [comment]
Updating to v5 is on my radar. Thanks for opening the issue. There are a few other fixes I’m working on before I publish the next preview.

**Comment by rasmusbjoernrasmussen** [comment]
@dansiegel, Thx a ton - for now i just mocked it locally to continue dev. 
Looking forward to new previews.

**Comment by dansiegel** [comment]
This has been updated and will be in the next preview
