### ISSUE TITLE
It refused to install in android project

### ISSUE THREAD

**Issue by chrisgate** [dansiegel/AzureMobileClient.Helpers#17]
I am use Net Standard 2.0

**Comment by chrisgate** [comment]
Sorry i was installing it without installing the real SDK ..............my bad

**Comment by dansiegel** [comment]
Sounds like you got this figured out then. If you're still having issues let me know.

**Comment by chrisgate** [comment]
Hi ....Alot have change since u wrote the TodoListDemo and what u wrote on the read me.

can u specific how to register " AwesomeAppCloudServiceOptions andAwesomeAppCustomerAppContext"
in DryIoc as specified on the read me............Please ,this is urgent @dansiegel .


Thanks

**Comment by dansiegel** [comment]
@chrisgate this is all open source. I'm quite busy right now so I can't say when I can get to update examples. Paying clients have to come first.

**Comment by chrisgate** [comment]
Ofcourse @dansiegel .............Thanks

**Comment by chrisgate** [comment]
when i have it workout i will send you update on the example.............cheers

**Comment by chrisgate** [comment]
Honestly i missed your QuickStartTemplate bcoz i can get to your head thru it bcoz u used most of these tools in it......now that is shutdown i am left with try and error till i get it right.

**Comment by dansiegel** [comment]
The QuickStart Templates are still available and actually should give you the updated example you're looking for... I've simply moved it from GitHub because there is really cool stuff I want to do that I can't do if the tooling is open source. You can still install the QuickStart Templates on any platform using the DotNet CLI or access them in the Visual Studio Mac Extension Gallery.

**Comment by chrisgate** [comment]
Can i beg you for something @dansiegel ......can you use this below code to create a compiled Project with quickstart template (tested UWP). and send zip to chrisgate01@gmail.com

" dotnet new prismforms -id com.dink.smartevents -app SmartEvents -acr true -data AzureMobileClient  -auth AAD
B2C -maps Maps -acr true"

At your own time.......no pressure .

Thanks in anticipations

Chris.
