### ISSUE TITLE
do i need this line in App.xaml  containerRegistry.RegisterSingleton<ILoginProvider<AADAccount>, LoginProvider>();

### ISSUE THREAD

**Issue by chrisgate** [dansiegel/AzureMobileClient.Helpers#19]
Hi @dansiegel ,
 Since i am not using Active Directory do i need this line:
 containerRegistry.RegisterSingleton<ILoginProvider<AADAccount>, LoginProvider>();

I am getting this error using the sample:  Exception - High: DryIoc.ContainerException: Unable to resolve Object {RequiredServiceType=Dink.SmartEvents.ViewModels.MainPageViewModel} with 0 arg(s) 
  in wrapper Func<Xamarin.Forms.Page, Object> {RequiredServiceType=Dink.SmartEvents.ViewModels.MainPageViewModel} with 0 arg(s) 
  from container.

I am learning how to PR so that as soon i get all these tool sample right, i will just file for update sample or documentation.....good way to give back to community.

Everything is okay on my sample but i commented that line off bcoz i dont know what should be in LoginProvider file.

Thanks

**Comment by dansiegel** [comment]
You need it if you're doing authentication. If you're not using authentication like in my TodoList example then you don't need it.

**Comment by chrisgate** [comment]
@dansiegel Thanks

**Comment by chrisgate** [comment]
I do need authentication but i am unable to make it work bcos ICloudService doesnt allow my View viewmodel to work...........so i want to handle the auth myself.

**Comment by chrisgate** [comment]
@dansiegel like your tododemo everything work fine without Authentication ............when usingAuthentication....... .in the latest pre version u turn ICloudService to generic of TAccount.............what break changes are we looking and  TAccount should MobileAppUser or AADAccount both in DryIoc registration and injection  ?

Thanks
