### ISSUE TITLE
Xamarin.Auth, latest Prism, and Unity problem 

### ISSUE THREAD

**Issue by powerdude** [dansiegel/AzureMobileClient.Helpers#20]
Hey Dan,

Have you tried this library with a UWP app and latest Prism.  I'm getting conflicts due to Unity:

```
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1700,5): error APPX1101: Payload contains two or more files with the same destination path 'Unity.Abstractions.dll'. Source files: 
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1700,5): error APPX1101: C:\Users\admin\.nuget\packages\unity\5.7.3\lib\netstandard2.0\Unity.Abstractions.dll
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1700,5): error APPX1101: C:\Users\admin\.nuget\packages\unity.abstractions\3.3.0\lib\netstandard2.0\Unity.Abstractions.dll
```

Any ideas?

cliff

**Comment by dansiegel** [comment]
Yeah I'm guessing you're using the Unity package from this repo... at the time I last published it I was in sync with what Prism used for Unity which was the Unity NuGet. That has since changed to Unity.Container which is why you're getting two identical references. I'll make a note of this and try to get an updated package out later this week.

**Comment by dansiegel** [comment]
btw feel free to send a PR on this as well :)

**Comment by powerdude** [comment]
one quick noob question, how do i use the Directory.build.props to create a local package without editing the project files?

**Comment by dansiegel** [comment]
Directory.build.props simply provide common properties across multiple projects. Creating NuGet packages on build is a feature of the new SDK Style projects. This [post](https://dansiegel.net/post/2018/03/29/net-standard-and-the-new-project-format-for-xamarin-developers) may help you.

**Comment by powerdude** [comment]
thanks, i had already sorted it.  should've removed the comment.
